name: Build and deploy Python app to Azure Web App - az-thailand

on:
  workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: | 
          az acr build --registry azthailand --image azthailand.azurecr.io/py-rag:0.0.1 .
        working-directory: ./src
          